### ISSUE TITLE
希望能够解决横屏异常显示问题

### ISSUE THREAD

**Issue by sejohng** [kirklin/cpdaily#22]
一不小心横屏就会异常显示(如图1)；且原版今日校园不支持横屏功能，建议禁用；此外出现了显示错位的问题(如图2)

![Screenshot_2020-11-14-10-38-15-175_com wisedu cpdaily2](https://user-images.githubusercontent.com/35053995/99138465-a6feba80-266b-11eb-93f0-61b818068f7d.jpg)
![IMG_20201114_112114](https://user-images.githubusercontent.com/35053995/99138467-a9f9ab00-266b-11eb-898e-7c70a5667670.jpg)

**Comment by kirklin** [comment]
建议开启竖屏锁定
