### ISSUE TITLE
希望能更新一下新的界面

### ISSUE THREAD

**Issue by qiqifuniu** [kirklin/cpdaily#24]
今日校园今天更新到新界面了
![Screenshot_20201116_151002_com wisedu cpdaily_edit_275985829854762](https://user-images.githubusercontent.com/62545619/99222648-f4228e00-281d-11eb-8623-9ea5e180dcf3.jpg)

**Comment by kirklin** [comment]
您好，目前最新版只提供定制服务，价格99元。需要的话请点开我的主页发邮件给我
