### ISSUE TITLE
想学习一下大佬的代码

### ISSUE THREAD

**Issue by wwx1996** [kirklin/cpdaily#8]
发现.databinding好像没有

**Comment by wwx1996** [comment]
> 发现.databinding好像没有

**Comment by kirklin** [comment]
欢迎查阅谷歌Jetpack库的官方文档https://developer.android.google.cn/jetpack/androidx/explorer

**Comment by wwx1996** [comment]
> 欢迎查阅谷歌Jetpack库的官方文档https://developer.android.google.cn/jetpack/androidx/explorer

谢过大佬
